#!/usr/bin/env ruby

################################
# Example 02 - ruby $LOAD_PATH #
################################


# ONE - Fails because functions isn't in the load path (ruby 1.9.3 and later)
require 'functions'

# TWO - Find out what we have in our load path
#puts $LOAD_PATH

# THREE - Works if we are in the example_01 folder (1.9.2 and older behavior)
#$LOAD_PATH.push('.')
#puts require 'functions'

# FOUR - Add our specific directry to the load path
#directory = File.dirname(__FILE__)
#$LOAD_PATH.push(directory)
#puts require 'functions'

# FIVE - Require the relative location of the file (OK if file does not move)
#puts require_relative 'functions'
