#!/usr/bin/env ruby

######################################
# Example 03 - rubygems & $LOAD_PATH #
######################################


# ONE - load thor rubygem (why does this work, it's NOT in our path)
puts require 'thor'

# TWO - Look for at our load paths
#puts $LOAD_PATH.any? { |path| File.exist?("#{path}/thor") }

# THREE - Look at our load paths after require
#require 'thor'
#puts $LOAD_PATH

# FOUR - load some more
#require 'bundler'
#require 'powder'
#puts $LOAD_PATH

# FIVE - Inspect our Gem paths
#puts Gem.path

# SIX - Find the path of our thor library
#`open #{Gem.path.last}`
